version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 897729109985.dkr.ecr.eu-west-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t --no-cache my-app-image .
      - echo Tagging the Docker image...
      - docker tag my-app-image:latest 897729109985.dkr.ecr.eu-west-1.amazonaws.com/alex_it_infra_project:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 897729109985.dkr.ecr.eu-west-1.amazonaws.com/alex_it_infra_project:latest
      - echo Docker image pushed successfully.

artifacts:
  files:
    - '**/*'
