version: 0.2

env:
  variables:
    DOCKER_HUB_EMAIL: "Alexander.Buerklen@Student.HTW-Berlin.de"
    DOCKER_HUB_PASSWORD: "Alex13ander" 

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 897729109985.dkr.ecr.eu-west-1.amazonaws.com
      - echo Logging in to Docker Hub...
      - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_EMAIL --password-stdin

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-app-image .
      - docker tag my-app-image:latest 897729109985.dkr.ecr.eu-west-1.amazonaws.com/alex_it_infra_project
      - docker tag my-app-image:latest $DOCKER_HUB_EMAIL/my-app-image:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 897729109985.dkr.ecr.eu-west-1.amazonaws.com/alex_it_infra_project
      - echo Pushing the Docker image to Docker Hub...
      - docker push $DOCKER_HUB_EMAIL/my-app-image:latest

artifacts:
  files:
    - '**/*'
