Parameters:
  InstanceVersion:
    Type: String
    Default: "latest"

Resources:
  AlexBLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      InstanceType: t2.micro
      ImageId: ami-03ca36368dbc9cfa1
      SecurityGroups:
        - !Ref AlexBSecurityGroup
      IamInstanceProfile: !Ref AlexBEC2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "Updating system packages..."
          yum update -y
          echo "Installing Docker..."
          dnf install docker -y
          echo "Starting Docker..."
          systemctl start docker
          echo "Adding ec2-user to Docker group..."
          usermod -a -G docker ec2-user

          echo "Logging into Amazon ECR..."
          $(aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 897729109985.dkr.ecr.eu-west-1.amazonaws.com)

          echo "Pulling the latest Docker image..."
          docker pull --quiet --disable-content-trust=true 897729109985.dkr.ecr.eu-west-1.amazonaws.com/alex_it_infra_project:${InstanceVersion}

          echo "Stopping any running containers..."
          docker stop $(docker ps -q --filter ancestor=897729109985.dkr.ecr.eu-west-1.amazonaws.com/alex_it_infra_project:${InstanceVersion}) || true

          echo "Removing the old Docker image..."
          docker rmi 897729109985.dkr.ecr.eu-west-1.amazonaws.com/alex_it_infra_project:${InstanceVersion} || true

          echo "Running the new Docker container..."
          docker run -d -p 80:8080 --rm 897729109985.dkr.ecr.eu-west-1.amazonaws.com/alex_it_infra_project:${InstanceVersion}

  AlexBAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref AlexBLaunchConfiguration
      MinSize: 1
      MaxSize: 3
      DesiredCapacity: 2
      AvailabilityZones: !GetAZs ''
      TargetGroupARNs:
        - !Ref AlexBTargetGroup
      Tags:
        - Key: Name
          Value: AlexBEC2Instanz
          PropagateAtLaunch: true
    DependsOn: AlexBSecurityGroup

  AlexBLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    DependsOn: AlexBSecurityGroup
    Properties:
      Name: AlexBLoadBalancer
      Scheme: internet-facing
      Type: application
      SecurityGroups:
        - !Ref AlexBSecurityGroup
      Subnets: 
        - subnet-0df5f35e24f2ad1b5
        - subnet-0fe0163065a6cc46b
      Tags:
        - Key: Name
          Value: AlexBLoadBalancer

  AlexBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: AlexBTargetGroup
      Protocol: HTTP
      Port: 80
      TargetType: instance
      VpcId: 'vpc-0acfaa03995941f03'
      HealthCheckEnabled: true

  AlexBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AlexBTargetGroup
      LoadBalancerArn: !Ref AlexBLoadBalancer
      Port: 80
      Protocol: HTTP

  AlexBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access
      VpcId: 'vpc-0acfaa03995941f03'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  AlexBEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref AlexBECRAccessRole

  AlexBECRAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ECRAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:GetAuthorizationToken
                Resource: "*"
